apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-luo1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-luo1
    app.kubernetes.io/part-of: cin4s-839-0044-app
  name: devfile-sample-luo1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-luo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-luo1
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0044-tenant/cin4s-839-0044-app/devfile-sample-luo1@sha256:720514a5e9ff4d6952a2e6d0ee49f6dcacb681086a7f7a537964e2863741bd61
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
